baseURL: "https://murat.github.io"
languageCode: "en-us"
theme: "rocinante"
title: "muratbastas"

paginate: 12

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2
    style: monokailight
  goldmark:
    renderer:
      unsafe: true

params:
  about: 'Murat Bastas | Software Developer [@Vispera](https://vispera.co).'
  links:
    - link:
        - name: Resume
          href: /resume.pdf
        - name: Email
          href: /contact
          smart_email_link: true
    - link:
        - name: Github
          href: 'https://github.com/murat'
          new_tab: true
        - name: Twitter
          href: 'https://twitter.com/muratbastas'
          new_tab: true
        - name: LinkedIn
          href: 'https://linkedin.com/in/muratbastas'
          new_tab: true

taxonomies:
  author: authors
  tag: tags

permalinks:
  post: "/:year/:month/:day/:slug/"
